### ISSUE TITLE
About unconnected nodes

### ISSUE THREAD

**Issue by PaulLiuYZ** [tufts-ml/graph-generation-EDGE#6]
Hello, thanks for your great work!
I am trying to use EDGE in my own dataset, with many nodes, there is only one connected graph and some nodes are not connected with any other nodes, do you think EDGE can deal with this condition?
Thanks a lot if you can give me some advice!

**Comment by lipingliulp** [comment]
Yes, it works for graphs with disconnected components. In theory, the model describes the distribution over adjacency matrices. As long as your graph can be written in an adjacency matrix, you can fit a model over it.
